import 'dart:io';

class Global {
  static String? name;
  static String? email;
  static String? phone;
  static String? address1;
  static String? address2;
  static String? address3;
  static File? photoPath;
  static String? description;
  static String? discription1;
  static String? discription2;
  static String? software;
  static List technical = [];
  static String? Interest;
  static String? photo;
  static String? DOB;
  static String? Nationality;
  static String? MaritalStatus;
  static String? Language;
  static String? Education;
  static String? School;
  static String? CGPA;
  static String? Year;
  static String? Company;
  static String? Roles;
  static String? Quality;
  static String? DateJoined;
  static String? DateExit;
  static String? DOB2;
  static String? Exit;
  static String? ProjectTitle;
  static String? Technologies1;
  static String? Roles2;
  static String? Technologies;
  static String? ProjectDescription;
  static String? Achievements;
  static String? Reference;
  static String? Designation;
  static String? Organization;
  static String? description2;
  static String? date;
  static String? place;
}
